# Generated by Django 5.0.6 on 2024-07-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_delete_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Topshiriq', 'verbose_name_plural': 'Topshiriqlar'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Tavsif:'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name="O'chirildi"),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha:'),
        ),
    ]
